Replace Maven build and test steps with DotNET commands

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,19 +30,35 @@ jobs:
         env:
           NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
           NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-  
-      - name: Run Tests and Generate JaCoCo Report
-        run: mvn -B clean test    
 
-      - name: Unit & Integration Tests (JUnit)
-        run: mvn verify -DskipUnitTests=false # 'verify' runs both unit (surefire) and integration (failsafe) tests
-
-      - name: Code Coverage (JaCoCo)
-        run: mvn jacoco:report
-
-      - name: Upload Test Results
+      - name: Build
+        run: dotnet build --configuration Release
+        
+      - name: Test
+        run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
+        
+      - name: Test Report
+        uses: dorny/test-reporter@v1
         if: always()
-        uses: actions/upload-artifact@v4
         with:
-          name: test-reports
-          path: target/surefire-reports/  
+          name: DotNET Tests
+          path: "**/test-results.trx"                            
+          reporter: dotnet-trx
+          fail-on-error: true
+
+          
+      # - name: Run Tests and Generate JaCoCo Report
+      #   run: mvn -B clean test    
+
+      # - name: Unit & Integration Tests (JUnit)
+      #   run: mvn verify -DskipUnitTests=false # 'verify' runs both unit (surefire) and integration (failsafe) tests
+
+      # - name: Code Coverage (JaCoCo)
+      #   run: mvn jacoco:report
+
+      # - name: Upload Test Results
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: test-reports
+      #     path: target/surefire-reports/  
